[Missions] Finalise la validation des formulaires
MTES-MCT/monitorfish pull request #2265
Opened 2023-06-30 07:20 UTC by ivangabriele

## Linked issues

- Resolve #2117
- Resolve #2191
- Resolve #2261
- Resolve #2268

----

- [ ] Tests E2E (Cypress)

2023-06-30 08:55 UTC, louptheron commented on frontend/src/features/SideWindow/MissionForm/index.tsx
> +  valideMissionForms,
validateMissionForms ?

2023-06-30 08:55 UTC, louptheron commented on frontend/src/features/SideWindow/MissionForm/ActionForm/schemas.ts
> +  gearWasControlled: boolean().required("Veuillez indiquer si l' engins a été contrôlé.")
Typo : "l' engins"

2023-06-30 08:55 UTC, louptheron commented on frontend/src/features/SideWindow/MissionForm/ActionForm/schemas.ts
> +    emitsVms: string().required('Veuillez indiquer si le navire émet un signal VMS.'),
On peut pas sortir tous checks et faire un concat ? car ce sont les mêmes quand dans `LandControlFormClosureSchema`

2023-06-30 08:55 UTC, louptheron commented on frontend/src/features/SideWindow/MissionForm/utils.tsx
> +export function valideMissionForms(
Un test Cypress pour valider l'affichage des erreurs ? Pas forcément toutes mais à minima 1 ou deux

2023-06-30 09:02 UTC, ivangabriele commented on frontend/src/features/SideWindow/MissionForm/ActionForm/schemas.ts
> +    emitsVms: string().required('Veuillez indiquer si le navire émet un signal VMS.'),
Oui j'y ai pensé mais je trouve ça plus clair de répéter. Trop de DRY pour ce qui est déclaratif a tendance à complexifier la compréhension (comme dans les props d'un composants par exemple où on ne "dry" généralement pas les props de composants custom similaires).

2023-07-04 14:58 UTC, louptheron requested changes
J'ai des comportements un peu bizarre avec la validation, globalement, j'ai l'impression qu'il y a pas mal de race condition.
Je pense qu'il faut vraiment limiter l'affichage des erreurs utilisateurs, par exemple pour l'erreur utilisateur sur une fonction debounced qui check un state local (i.e la fonction `validateMissionFormsLiveValues`), c'est un souci d'architecture de code j'ai l'impression (vu qu'il arrive).

Bug:
- Quand j'édite la mission du "15 mars 23, 10:22" (dans "Toutes les missions"), cela ne met pas pas l'unité manquante en route (il n'y a pas de validation), de plus, je peux enregistrer cette mission alors qu'elle est invalide.

2023-07-04 14:58 UTC, louptheron commented on frontend/src/features/SideWindow/MissionForm/index.tsx
> +    [mainFormValues?.endDateTimeUtc, mainFormValues?.startDateTimeUtc]
Il y a d'autres champs qui peuvent changer et qui sont validés dans le `mainForm`, ces deps sont trop restrictives

2023-07-04 15:25 UTC, louptheron commented
Pour info, concernant le test commenté (https://github.com/MTES-MCT/monitorfish/pull/2265/commits/d37287452eb72aa52fdcda17856e8462a9e17fd1#diff-bbd84326ea5336535c36e0b4209b2253ffd999cc8000dd970004d18ca078272bL41), j'ai rajouté la façade MEMN pour que ça soit plus clair, mais c'était bien normal que la valeur soit à `null`.

2023-07-10 07:59 UTC, ivangabriele commented on frontend/src/features/SideWindow/MissionForm/index.tsx
> +    [mainFormValues?.endDateTimeUtc, mainFormValues?.startDateTimeUtc]
Comme je l'ai mis en comment ça ne sert qu'à revalider les erreurs dans les actions "non visibles", ça n'a aucun rapport avec les checks de validation live qui eux sont en temps réel grâce à la prop `isValid` qui est mis à jour à chaque onChange. Cela ne peut arriver que si les dates changent.

Je pourrais par contre virer le `setMainFormValues(nextMainFormValues)` et n'appliquer la validation que dans les formulaires invisibles.

2023-07-10 14:50 UTC, merged