[Préavis] Calculer le type de PNO, les segments et la note de risque pour les préavis manuels
MTES-MCT/monitorfish pull request #3263
Opened 2024-06-05 09:42 UTC by louptheron

## Linked issues

- Resolve #3240

----

- [ ] Tests E2E (Cypress)

2024-06-11 16:21 UTC, VincentAntoine commented on backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/entities/risk_factor/VesselRiskFactor.kt
>  const val defaultRiskFactor = 1.4
Attention les `**` sont des puissances, pas des multiplications dans le code python. Le facteur de risque par défaut vaut 1**0.2 * 2**0.3 * 2**0.5 = 1.7411011265922485

2024-06-12 09:37 UTC, VincentAntoine requested changes

2024-06-12 09:37 UTC, VincentAntoine commented on backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/ComputeRiskFactor.kt
> +        val storedRiskFactor = riskFactorRepository.findByInternalReferenceNumber(portLocode)
typo ?

`.findByInternalReferenceNumber(portLocode)`
plutôt :
`.findByInternalReferenceNumber(vesselCfr)`

2024-06-12 09:37 UTC, VincentAntoine commented on backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/ComputeRiskFactorUTests.kt
> +        given(riskFactorRepository.findByInternalReferenceNumber(portLocode)).willReturn(null)
idem, `.findByInternalReferenceNumber(vesselCfr)` au  lieu de `.findByInternalReferenceNumber(portLocode)` ?

2024-06-12 09:37 UTC, VincentAntoine commented on backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/ComputeRiskFactorUTests.kt
> +        given(riskFactorRepository.findByInternalReferenceNumber(portLocode)).willReturn(null)
idem

2024-06-12 09:37 UTC, VincentAntoine commented on backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/ComputeRiskFactorUTests.kt
> +        given(riskFactorRepository.findByInternalReferenceNumber(portLocode)).willReturn(storedRiskFactor)
idem

2024-06-12 09:37 UTC, VincentAntoine commented on backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/ComputeRiskFactorUTests.kt
> +        given(riskFactorRepository.findByInternalReferenceNumber(portLocode)).willReturn(null)
idem

2024-06-12 09:37 UTC, VincentAntoine commented on backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/ComputeRiskFactorUTests.kt
> +        given(riskFactorRepository.findByInternalReferenceNumber(portLocode)).willReturn(storedRiskFactor)
idem

2024-06-12 09:37 UTC, VincentAntoine commented on backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/TestUtils.kt
> +                    id = 1,
C'est sans doute sans importance mais toutes les `PnoTypeRule`s ont le même `id`.

2024-06-12 09:37 UTC, VincentAntoine commented on backend/src/main/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/ComputePnoTypes.kt
> +        return containsSpecies && containsGear && containsFaoAreas && containsFlagState
cf discussion pour rendre la logique compatible avec des `pnoTypeRule` qui combinent engins et / ou  espèces et / ou zones FAO et / ou pavillons

2024-06-12 12:53 UTC, louptheron commented on backend/src/test/kotlin/fr/gouv/cnsp/monitorfish/domain/use_cases/prior_notification/TestUtils.kt
> +                    id = 1,
Yes ce n'était pas testé dans les tests, mais allez je le modifie pour pas d'ambiguité

2024-06-12 14:32 UTC, VincentAntoine approved these changes

2024-06-12 14:42 UTC, merged